data:
  dataset_dir: "Cityscapes"
  name: "cityscapes"
  num_parallel_workers: 8
  map_label: [0.8373, 0.918, 0.866, 1.0345,
              1.0166, 0.9969, 0.9754, 1.0489,
              0.8786, 1.0023, 0.9539, 0.9843,
              1.1116, 0.9037, 1.0865, 1.0955,
              1.0865, 1.1529, 1.0507]
  ignore_label: 255
  train_transforms:
    item_transforms:
      - RandomResizeCrop: {
      crop_size: [1024, 1024], 
      multi_scale: True, 
      base_size: 2048, 
      ignore_label: 255}
      - RandomFlip: { prob: 0.5 }
      - RandomColor: { contrast_range: [0.4, 1.6] }
      - Normalize: { 
      is_scale: True, 
      norm_type: 'mean_std',
      mean: [0.3257, 0.3690, 0.3223], 
      std: [0.2112, 0.2148, 0.2115] }
      - TransposeImage: { hwc2chw: True }

  eval_transforms:
    multi_scale: True
    img_ratios: [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
    flip: True
    item_transforms:
      - Resize: { target_size: [1024, 2048], keep_ratio: True, ignore_label: 255 }
      - Normalize: { is_scale: True, norm_type: 'mean_std',  mean: [0.3257, 0.3690, 0.3223], std: [0.2112, 0.2148, 0.2115] }
      - TransposeImage: { hwc2chw: True }
