__BASE__: [
  '../cityscapes.yml',
  '../optimizer_8k.yml',
]
net: OCRNet
num_classes: 19
backbone:
    initializer: hrnet_w48
    pretrained: True
    backbone_ckpt: "" # If on modelarts, set the name of checkpoint saved in data_url
    in_channels: 3
fcn_head:
    in_channels: [32, 64, 128, 256]
    channels: 480
    kernel_size: 1
    num_convs: 1
    concat_input: False
    in_index: [0, 1, 2, 3]
    norm: "bn"
    act: "relu"
ocr_head:
    in_channels: [32, 64, 128, 256]
    channels: 512
    in_index: [0, 1, 2, 3]
    ocr_channels: 256
    norm: "bn"
    act: "relu"
loss_weight: [1.0, 0.4]
